# Generated by Django 3.0.7 on 2020-09-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='car_id',
            new_name='pet_id',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='car_title',
            new_name='pet_title',
        ),
    ]
