# Generated by Django 3.0.7 on 2020-09-14 15:13

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_title', models.CharField(max_length=255)),
                ('pet_type', multiselectfield.db.fields.MultiSelectField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=7)),
                ('pet_breed', multiselectfield.db.fields.MultiSelectField(choices=[('Labrador Retriever(dog)', 'Labrador Retriever(dog)'), ('German Shepherd(dog)', 'German Shepherd Dog(dog)'), ('Golden Retriever(dog)', 'Golden Retriever(dog)'), ('Bulldog(dog)', 'Bulldog(dog)'), ('Beagle(dog)', 'Beagle(dog)'), ('British Shorthair(cat)', 'British Shorthair(cat)'), ('Persian Cats(cat)', 'Persian Cats(cat)'), ('Maine Coon(cat)', 'Maine Coon(cat)'), ('American Shorthair(cat)', 'American Shorthair(cat)'), ('Scottish Fold(cat)', 'Scottish Fold(cat)')], max_length=191)),
                ('color', models.CharField(max_length=100)),
                ('age', multiselectfield.db.fields.MultiSelectField(choices=[('Puppy/Kitten', 'Puppy/Kitten'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=31)),
                ('gender', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.IntegerField()),
                ('pet_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('pet_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('pet_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('pet_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('pet_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
