# Generated by Django 3.0.7 on 2020-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20200914_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
